swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /circuit:
    get:
      operationId: Circuit
      responses:
        "200":
          description: ""
  /circuit1:
    get:
      operationId: Circuit1
      responses:
        "200":
          description: ""
