language: go
sudo: required
go:
  - 1.11
install: true

jobs:
  include:
    - stage: Format Checker
      script: bash scripts/travis/formatChecker.sh
    - stage: DeadCode Checker
      script:
        - go get -u github.com/tsenart/deadcode
        - bash scripts/travis/deadCodeChecker.sh
    - stage: Misspell Checker
      script:
        - go get -u github.com/client9/misspell/cmd/misspell
        - bash scripts/travis/misspellChecker.sh
    - stage: GoConst Checker
      script:
        - go get -u github.com/jgautheron/goconst/cmd/goconst
        - bash scripts/travis/goConstChecker.sh
    - stage: GoLint Checker
      script:
        - go get -u github.com/golang/lint/golint
        - bash scripts/travis/goLintChecker.sh
    - stage: GoCyclo Checker
      script:
        - go get github.com/fzipp/gocyclo
        - bash scripts/travis/goCycloChecker.sh