language: go
sudo: required
go:
  - 1.11
install: true

before_script:
  - mkdir -p $HOME/gopath/src/github.com/mi4tin/go-chassis-gate
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/mi4tin/go-chassis-gate/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/mi4tin/go-chassis-gate
  - cd $HOME/gopath/src/github.com/mi4tin/go-chassis-gate

jobs:
  include:
    - stage: Unit Test
      script:
        - bash scripts/travis/start_latest_sc.sh
        - go get github.com/stretchr/testify
        - go get github.com/mattn/goveralls
        - go get golang.org/x/tools/cmd/cover
        - GO111MODULE=on go mod download
        - GO111MODULE=on go mod vendor
        - bash $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci
    - stage: Build
      script:
        - GO111MODULE=on go mod download
        - GO111MODULE=on go mod vendor
        - go build -o chassisGate